repos:
  # pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace # Trim trailing whitespace
      - id: check-json # Attempt to load all json files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: double-quote-string-fixer # Replace double quoted strings with single quoted strings
      - id: end-of-file-fixer # Make sure files end in a newline and only a newline
      - id: fix-encoding-pragma # Remove the coding pragma: # -*- coding: utf-8 -*-
        args: ["--remove"]
      - id: mixed-line-ending # Replace or check mixed line ending
        args: ["--fix=auto"]
